import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :viche, VicheWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force SSL: redirects HTTP -> HTTPS and sets HSTS headers.
# Enabled by default for standalone deployments. Configurable via build-time env vars:
#
#   DISABLE_FORCE_SSL=true        — disable entirely (when behind a TLS-terminating proxy)
#   FORCE_SSL_EXCLUDE_HOSTS=a,b   — keep force_ssl but exempt specific hostnames
#                                   (e.g. Docker-internal names like "viche")
#
# Note: force_ssl is compile-time in Phoenix, so these are read during `mix release`.
# In Docker, pass them as build args.
unless System.get_env("DISABLE_FORCE_SSL") == "true" do
  exclude_hosts =
    System.get_env("FORCE_SSL_EXCLUDE_HOSTS", "")
    |> String.split(",", trim: true)

  config :viche, VicheWeb.Endpoint,
    force_ssl: [rewrite_on: [:x_forwarded_proto]],
    exclude: [
      hosts: ["localhost", "127.0.0.1"] ++ exclude_hosts
    ]
end

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
